services:

  postgres:
    image: postgres:16
    container_name: pep-postgres

    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: pep

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq

    ports:
      - "5672:5672"
      - "15672:15672"

    restart: unless-stopped

  hapi-fhir:
    image: hapiproject/hapi:latest
    container_name: hapi-fhir

    ports:
      - "8080:8080"

    volumes:
      - hapi_data:/data/hapi

    restart: unless-stopped

  api:
    build:
      context: ./clinical-microservice

    container_name: clinical-api

    depends_on:
      - postgres
      - rabbitmq

    env_file:
      - .env

    ports:
      - "8000:8000"

    restart: unless-stopped

  consumer:
    build:
      context: ./clinical-consumer

    container_name: clinical-consumer

    depends_on:
      - rabbitmq
      - hapi-fhir

    env_file:
      - .env

    restart: unless-stopped

volumes:
  postgres_data:
  hapi_data: